AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  SalesforceMarketingFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: 595245034069.dkr.ecr.ap-south-1.amazonaws.com/salesforce-marketing-lambda:latest
      Timeout: 60
      MemorySize: 512
