AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 900
    MemorySize: 512

Resources:
  IcebergIncrementalLoaderLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: IcebergIncrementalLoaderLambda
      PackageType: Image
      Architectures:
        - x86_64
      ImageUri: !Sub 595245034069.dkr.ecr.ap-south-1.amazonaws.com/iceberg-lambda-repo:latest
      Role: arn:aws:iam::595245034069:role/salesforce-lambda-execution