version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Uploading Glue scripts to S3..."
      - aws s3 cp glue-jobs/parquet-cleaner-job/script.py s3://glue-script-salesforce/parquet-cleaner-job/script.py
      - echo "Updating Glue job:parquet-cleaner-job"
      - aws glue update-job --job-name parquet-cleaner-job --job-update '{"Role":"arn:aws:iam::595245034069:role/codebuildrole","Command":{"ScriptLocation":"s3://glue-script-salesforce/parquet-cleaner-job/script.py", "Name":"parquet-cleaner-job"}}'