version: 0.2

env:
  variables:
    ECR_REPOSITORY: salesforce-marketing-lambda
    AWS_DEFAULT_REGION: ap-south-1
    PROJECT_DIR: salesforce-marketing-data-generation
    LAMBDA_FUNCTION_NAME: SalesforceMarketingDataGenLambda
    STACK_NAME: salesforce-marketing-lambda-stack

phases:
  install:
    commands:
      - pip install aws-sam-cli
      - sudo apt-get install -y jq

  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 595245034069.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - TIMESTAMP=$(date +%Y%m%d%H%M%S)
      - IMAGE_TAG=${COMMIT_HASH}-${TIMESTAMP}

  build:
    commands:
      - cd $PROJECT_DIR && docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
      - docker tag $ECR_REPOSITORY:$IMAGE_TAG 595245034069.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
      - docker tag $ECR_REPOSITORY:$IMAGE_TAG 595245034069.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY:latest

  post_build:
    commands:
      - docker push 595245034069.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
      - docker push 595245034069.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY:latest
      - sam deploy --template-file template.yaml --stack-name $STACK_NAME --image-repository 595245034069.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY --parameter-overrides ECRRepository=$ECR_REPOSITORY ImageTag=$IMAGE_TAG --capabilities CAPABILITY_NAMED_IAM --region $AWS_DEFAULT_REGION --no-confirm-changeset --no-fail-on-empty-changeset
      - |
        MAX_RETRIES=5
        SLEEP_INTERVAL=20
        RETRIES=0
        SUCCESS=0
        while [ $RETRIES -lt $MAX_RETRIES ]; do
          echo "Checking deployed image URI... (Attempt $((RETRIES+1)))"
          DEPLOYED_IMAGE=$(aws lambda get-function --function-name $LAMBDA_FUNCTION_NAME --query 'Configuration.Code.ImageUri' --output text 2>/dev/null || true)
          if [ -n "$DEPLOYED_IMAGE" ] && echo "$DEPLOYED_IMAGE" | grep -q "$IMAGE_TAG"; then
            echo "✅ Deployment verified successfully: $DEPLOYED_IMAGE"
            SUCCESS=1
            break
          else
            echo "⏳ Image tag mismatch or unavailable yet. Expected: $IMAGE_TAG, Got: $DEPLOYED_IMAGE"
            sleep $SLEEP_INTERVAL
            RETRIES=$((RETRIES+1))
          fi
        done

        if [ $SUCCESS -ne 1 ]; then
          echo "❌ Deployment verification failed after $MAX_RETRIES attempts!"
          aws cloudformation describe-stack-events --stack-name $STACK_NAME --region $AWS_DEFAULT_REGION --max-items 20
          exit 1
        fi

artifacts:
  files:
    - $PROJECT_DIR/template.yaml
