AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Salesforce Marketing Lambda Container Function

Resources:
  SalesforceMarketingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SalesforceMarketingDataGenLambda
      PackageType: Image
      ImageUri: 595245034069.dkr.ecr.ap-south-1.amazonaws.com/salesforce-marketing-lambda:latest
      Timeout: 60
      MemorySize: 512
      Role: arn:aws:iam::595245034069:role/salesforce-lambda-execution
