version: 0.2

phases:
  build:
    commands:
      - echo "Uploading script to S3..."
      - aws s3 cp glue-jobs/salesforce-iceberg-incremental/script.py s3://glue-script-salesforce/salesforce-iceberg-incremental/script.py
      - echo "Updating Glue job:salesforce-iceberg-incremental"
      - aws glue update-job --job-name salesforce-iceberg-incremental --job-update "{\"Role\":\"arn:aws:iam::595245034069:role/codebuildrole\",\"ExecutionProperty\":{\"MaxConcurrentRuns\":1},\"Command\":{\"Name\":\"glueetl\",\"ScriptLocation\":\"s3://glue-script-salesforce/salesforce-iceberg-incremental/script.py\",\"PythonVersion\":\"3\"},\"MaxRetries\":0,\"Timeout\":2880,\"GlueVersion\":\"3.0\",\"WorkerType\":\"G.2X\",\"NumberOfWorkers\":10}"
