version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Uploading Glue scripts to S3..."
      - aws s3 cp glue-jobs/salesforce-iceberg-incremental/script.py s3://glue-script-salesforce/salesforce-iceberg-incremental/script.py

      - echo "Updating Glue job: salesforce-iceberg-incremental"
      - aws glue update-job --job-name salesforce-iceberg-incremental \
          --job-update '{"Command": {"ScriptLocation": "s3://glue-script-salesforce/salesforce-iceberg-incremental/script.py"}}'
